import { existsSync, writeFileSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import { spawn } from "node:child_process";
import { homedir } from "node:os";
import { PROJECT_ROOT, ICON_ICO, launchVbsPath } from "./paths.ts";

const SHORTCUT_NAME = "Service Runner.lnk";

export function startupDir(): string {
  return (
    process.env.APPDATA
      ? join(process.env.APPDATA, "Microsoft", "Windows", "Start Menu", "Programs", "Startup")
      : join(homedir(), "AppData", "Roaming", "Microsoft", "Windows", "Start Menu", "Programs", "Startup")
  );
}

export function shortcutPath(): string {
  return join(startupDir(), SHORTCUT_NAME);
}

export function launchDetached(): void {
  const vbs = writeLaunchVbs();
  const child = spawn("wscript.exe", [vbs], {
    detached: true,
    stdio: "ignore",
    windowsHide: true,
    cwd: PROJECT_ROOT,
  });
  child.unref();
}

export function writeLaunchVbs(): string {
  const node = process.execPath;
  const tsx = join(PROJECT_ROOT, "node_modules", "tsx", "dist", "cli.mjs");
  const entry = join(PROJECT_ROOT, "src", "index.ts");
  const vbs = launchVbsPath();
  const cmd = `"${node}" "${tsx}" "${entry}" --hidden`;
  const script = [
    "' Auto-generated by Service Runner. Not part of the git repo.",
    "Set sh = CreateObject(\"Wscript.Shell\")",
    `sh.CurrentDirectory = "${escVbs(PROJECT_ROOT)}"`,
    `sh.Run ${vbsQuote(cmd)}, 0, False`,
    "",
  ].join("\r\n");
  writeFileSync(vbs, script, "utf8");
  return vbs;
}

export async function installStartup(): Promise<string> {
  const vbs = writeLaunchVbs();
  const lnk = shortcutPath();
  const ico = existsSync(ICON_ICO) ? ICON_ICO : "";
  const ps = [
    `$wsh = New-Object -ComObject WScript.Shell`,
    `$lnk = $wsh.CreateShortcut(${psStr(lnk)})`,
    `$lnk.TargetPath = "wscript.exe"`,
    `$lnk.Arguments = ${psStr(`"${vbs}"`)}`,
    `$lnk.WorkingDirectory = ${psStr(PROJECT_ROOT)}`,
    `$lnk.WindowStyle = 7`,
    `$lnk.Description = "Service Runner — local process supervisor"`,
    ico ? `$lnk.IconLocation = ${psStr(ico)}` : "",
    `$lnk.Save()`,
  ]
    .filter(Boolean)
    .join("; ");
  await runPs(ps);
  return lnk;
}

export function uninstallStartup(): void {
  const lnk = shortcutPath();
  if (existsSync(lnk)) unlinkSync(lnk);
}

export function startupInstalled(): boolean {
  return existsSync(shortcutPath());
}

function escVbs(s: string): string {
  return s.replace(/"/g, '""');
}

function vbsQuote(cmd: string): string {
  return `"${escVbs(cmd)}"`;
}

function psStr(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function runPs(command: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(
      "powershell.exe",
      ["-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", command],
      { windowsHide: true, stdio: ["ignore", "pipe", "pipe"] },
    );
    let err = "";
    child.stderr?.on("data", (c) => {
      err += c.toString();
    });
    child.on("exit", (code) => {
      if (code === 0) resolve();
      else reject(new Error(err.trim() || `powershell exited ${code}`));
    });
    child.on("error", reject);
  });
}
